CREATE TABLE `users` (
 `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 `username` TEXT NOT NULL UNIQUE,
 `password` TEXT NOT NULL
);
INSERT INTO `users` (
  `username`,
  `password`
) VALUES (
  'travis',
  'mypassword'
)

CREATE TABLE `markers` (
 `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 `longitude` REAL NOT NULL,
 `latitude` REAL NOT NULL,
 'type' TEXT NOT NULL
);
INSERT INTO `markers` (
  `longitude`,
  `latitude`,
  `type`
) VALUES (
  'travis',
  'mypassword'
)
